<?php header('HTTP/1.1 503 Service Temporarily Unavailable'); header('Status: 503 Service Temporarily Unavailable'); header('Retry-After: 600'); ?>
<!doctype html>
<html <?php language_attributes(); ?> class="no-js">
	
	<head>
		<meta charset="<?php bloginfo('charset'); ?>">
		
		<title>
			<?php wp_title(''); ?>
			<?php if(wp_title('', false)) { echo ' :'; } ?> 
			<?php bloginfo('name'); ?>
		</title>

		<link href="//www.google-analytics.com" rel="dns-prefetch">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
		<link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type='text/css'>
        
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

		<!---
		Welcome to our free WordPress Maintenance Mode template by http://seedprod.com Get your free download at https://www.seedprod.com/how-to-create-custom-maintenance-mode-page-wordpress/
		This work is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License
		http://creativecommons.org/licenses/by-nc-nd/4.0/

		To get started follow this checklist.

		1. Replace the *Page Title* on lines 24, 32 & 297
		2. Set the *Page Description* on lines 27, 33 & 299
		3. Set an optional *Logo* on lines 295 using the src attribute.
		4. Set your *Facebook Profile* URL on line 313 using the href attribute.
		5. Set your *Twitter Profile* URL on line 314 using the href attribute.
		6. Set your *Email* on line 315 using the href attribute.
		7. Set your background image on line 64, see file README.mb for additional background images.
		8. Set your MailChimp email post URL on line 301 See video: https://youtu.be/YUdP1qfMot8
		9. FTP to your Website. 
		-->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<!-- 		<title>Maintenance Mode</title> -->

		<meta name="generator" content="seedprod.com 1.0.0" />
		<meta name="description" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="https://www.seedprod.com/wp-content/uploads/2016/01/cropped-site-icon-compressor-32x32.png">
		<meta property="og:url" content="" />
		<meta property="og:type" content="website" />
		<meta property="og:title" content="Uppdatering av hemsida" />
		<meta property="og:description" content="" />
		
		<!-- Calculated Styles -->
		<style type="text/css">
		

			html{
				height:100vh;
				overflow: hidden;
			}

			body {
				height:100vh;
				overflow: auto;
				-webkit-overflow-scrolling: touch;
			}
			
			h1 {
				margin: 0.5em 0;
				font-size: 2.5rem;
				font-family: 'VAGrounded', sans-serif;
				color: $color-green;
			}

			.errorwrapper {
				display: flex;
				justify-content: center;
				align-items: center;
				max-width: 740px;
				width: 100%;
				padding: 20px;
			}

		</style>
		
	</head>

	<body>

		<div class="errorwrapper">

			<img src="http://ensakitaget.se/wp-content/themes/ensakitaget/images/ensakitaget-logo.png">

			<h1>Underhållning av hemsidan</h1>

			<p>Just nu underhålls sidan så den mår topp, kom tillbaka om en stund så bör det vara klart</p>

		</div>

	</body>
</html>

<!-- This page was generated by ComingSoonPage.com | Learn more: http://www.comingsoonpage.com -->
